Update all snaps to core24 and rel39 base
Update all snaps to compile and run with core24 based packages and the
rel39 package repositories from nvidia.

Adapt all build steps to compile the new sources and adapt paths of all
provider wrappers.

Add missing interfaces for snaps to successfully run.

Signed-off-by: Sebastian Weyer <sebastian.weyer@canonical.com>

diff --git a/tensorrt-samples/snap/snapcraft.yaml b/tensorrt-samples/snap/snapcraft.yaml
--- a/tensorrt-samples/snap/snapcraft.yaml
+++ b/tensorrt-samples/snap/snapcraft.yaml
@@ -1,6 +1,6 @@
 name: tensorrt-samples # you probably want to 'snapcraft register <name>'
-base: core22 # the base snap is the execution environment for this snap
-version: '10.3.0.30-1+cuda12.5' # just for humans, typically '1.2+git' or '1.3.2'
+base: core24 # the base snap is the execution environment for this snap
+version: '11.0.0.114-1+cuda13.2' # just for humans, typically '1.2+git' or '1.3.2'
 summary: Tensorrt sample applications # 79 char long summary
 description: |
   Tensorrt sample applications to test the GPU
@@ -11,14 +11,14 @@ confinement: strict # use 'strict' once you have the right plugs and slots
 package-repositories:
   - type: apt
     components: [main]
-    suites: [r36.5]
+    suites: [r39.2]
     key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
     key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
-    url: https://repo.download.nvidia.com/jetson/t234
+    url: https://repo.download.nvidia.com/jetson/som
     architectures: [arm64]
   - type: apt
     components: [main]
-    suites: [r36.5]
+    suites: [r39.2]
     key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
     key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
     url: https://repo.download.nvidia.com/jetson/common
@@ -27,10 +27,12 @@ package-repositories:
 plugs:
   hardware-observe:
   opengl:
+  microstack-support:
+  network-bind:
   graphics-core22:
     interface: content
     target: $SNAP/graphics
-  tensorrt-libs-cuda-12:
+  tensorrt-libs-cuda-13:
     interface: content
     target: $SNAP/tensorrt-libs
 
@@ -40,40 +42,95 @@ apps:
       - bin/graphics-core22-wrapper
       - bin/tensorrt-libs-wrapper
     command: bin/execute_sample.sh
-    environment:
-      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/cuda-12.6/targets/aarch64-linux/lib
+
+layout:
+  /usr/local/cuda/targets/sbsa-linux/lib:
+    symlink: $SNAP/tensorrt-libs/usr/local/cuda-13.2/lib64
+  /usr/local/cuda-13.2/lib64:
+    symlink: $SNAP/tensorrt-libs/usr/local/cuda-13.2/lib64
 
 parts:
   tensorrt-samples:
     plugin: nil
+    source: https://github.com/NVIDIA/TensorRT.git
+    source-type: git
+    source-tag: release/11.0
+    build-snaps:
+      - cmake
     build-packages:
       - initramfs-tools
-      - cuda-12-6
+      - cuda-13-2
+      - unzip
+      - wget
         #- libnvinfer-bin
-      - libnvinfer-samples
-    stage-packages:
-      - libnvinfer-samples
     override-build: |
-      mkdir -p /opt/nvidia/l4t-packages/
-      touch /opt/nvidia/l4t-packages/.nv-l4t-disable-boot-fw-update-in-preinstall
-      L4T_DEB_PACKAGES_PATH=${L4T_DEB_PACKAGES_PATH:="NVIDIA_ARCHIVE"}
-      if [ "$L4T_DEB_PACKAGES_PATH" = "NVIDIA_ARCHIVE" ]; then
-        apt update
-        apt install --yes nvidia-l4t-dla-compiler nvidia-l4t-cuda
-      elif [ -d $L4T_DEB_PACKAGES_PATH ]; then
-        apt install --yes libegl1 -f
-        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-cuda_*.deb
-        # nvidia-l4t-dla-compiler is not part of the private set of Nvidia packages,
-        # that's why it is installed through the Nvidia archive.
-        apt install --yes nvidia-l4t-dla-compiler
+      wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/sbsa/cuda-keyring_1.1-1_all.deb
+      dpkg -i cuda-keyring_1.1-1_all.deb
+
+      apt update
+      TENSORRT_VERSION=11.0.0.114-1+cuda13.2
+      apt install -y tensorrt=$TENSORRT_VERSION \
+                     libnvinfer11=$TENSORRT_VERSION \
+                     libnvinfer-plugin11=$TENSORRT_VERSION \
+                     libnvinfer-vc-plugin11=$TENSORRT_VERSION \
+                     libnvinfer-lean11=$TENSORRT_VERSION \
+                     libnvinfer-dispatch11=$TENSORRT_VERSION \
+                     libnvonnxparsers11=$TENSORRT_VERSION \
+                     libnvinfer-bin=$TENSORRT_VERSION \
+                     libnvinfer-dev=$TENSORRT_VERSION \
+                     libnvinfer-lean-dev=$TENSORRT_VERSION \
+                     libnvinfer-plugin-dev=$TENSORRT_VERSION \
+                     libnvinfer-vc-plugin-dev=$TENSORRT_VERSION \
+                     libnvinfer-dispatch-dev=$TENSORRT_VERSION \
+                     libnvonnxparsers-dev=$TENSORRT_VERSION \
+                     python3-libnvinfer-dev=$TENSORRT_VERSION \
+                     libnvinfer-headers-python-plugin-dev=$TENSORRT_VERSION \
+                     libnvinfer-headers-dev=$TENSORRT_VERSION \
+                     libnvinfer-safe-headers-dev=$TENSORRT_VERSION \
+                     libnvinfer-headers-plugin-dev=$TENSORRT_VERSION \
+                     python3-libnvinfer=$TENSORRT_VERSION \
+                     python3-libnvinfer-lean=$TENSORRT_VERSION \
+                     python3-libnvinfer-dispatch=$TENSORRT_VERSION
+
+      mkdir build
+      cd build
+      cmake .. \
+          -DCMAKE_CUDA_COMPILER=/usr/local/cuda-13.2/bin/nvcc  \
+          -DCMAKE_BUILD_TYPE=Debug \
+          -DTRT_LIB_DIR=/usr/lib/aarch64-linux-gnu \
+          -DTRT_OUT_DIR=`pwd`/bin \
+          -DBUILD_SAMPLES=ON \
+          -DBUILD_PARSERS=OFF \
+          -DBUILD_PLUGINS=OFF \
+          -DTRT_PLATFORM_ID=aarch64
+      cmake --build . --parallel $(nproc)
+      mkdir -p $CRAFT_PART_INSTALL/usr/src/tensorrt/samples/
+      cp -ar samples/ $CRAFT_PART_INSTALL/usr/src/tensorrt
+      cp -ar bin/ $CRAFT_PART_INSTALL/usr/src/tensorrt
+
+      echo "Fetching tensorrt_sample_data URL"
+      if ! wget -q https://raw.githubusercontent.com/NVIDIA/TensorRT/release/11.0/samples/README.md; then
+        echo "Error: failed to fetch the tensorrt_sample_data URL"
+        exit 1
       fi
-      echo '/usr/local/cuda-12.6/compat' | tee -a /etc/ld.so.conf.d/000_cuda.conf
-      ldconfig
-      cd $CRAFT_PART_INSTALL/usr/src/tensorrt/samples
-      make
+      sample_data_url=$(grep -o "https://github.com/NVIDIA/TensorRT/releases/download/.*zip" README.md)
+      if [ -z "$sample_data_url" ]; then
+        echo "Error: sample_data_url is empty"
+        exit 1
+      fi
+      echo "Downloading tensorrt_sample_data"
+      if ! wget -q $sample_data_url; then
+        echo "Error: failed to download the tensorrt_sample_data"
+        rm -rf README.md
+        exit 1
+      fi
+      echo "Installing the TensorRT sample_data"
+      unzip tensorrt_sample_data_*.zip -d $CRAFT_PART_INSTALL/usr/src/tensorrt/data
+
     override-prime: |
       mkdir -p $CRAFT_PRIME/usr/src
       cp -r $CRAFT_STAGE/usr/src/tensorrt $CRAFT_PRIME/usr/src
+      craftctl default
 
   tensorrt-samples-list:
     plugin: dump
diff --git a/vpi-samples/snap/snapcraft.yaml b/vpi-samples/snap/snapcraft.yaml
--- a/vpi-samples/snap/snapcraft.yaml
+++ b/vpi-samples/snap/snapcraft.yaml
@@ -1,5 +1,5 @@
 name: vpi-samples
-base: core22
+base: core24
 version: 3.2.4-1
 summary: NVIDIA VPI samples
 description: |
@@ -14,49 +14,62 @@ plugs:
   graphics-core22:
     interface: content
     target: $SNAP/graphics
-  vpi3-core22:
+  vpi4-core24:
     interface: content
     target: $SNAP/vpi
+  system-files:
+    write:
+      - /proc/driver/nvidia/gpus
 
 package-repositories:
   - type: apt
     components: [main]
-    suites: [r36.5]
+    suites: [r39.2]
     key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
     key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
-    url: https://repo.download.nvidia.com/jetson/t234
+    url: https://repo.download.nvidia.com/jetson/som
     architectures: [arm64]
   - type: apt
     components: [main]
-    suites: [r36.5]
+    suites: [r39.2]
     key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
     key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
     url: https://repo.download.nvidia.com/jetson/common
     architectures: [arm64]
-  - type: apt
-    ppa: ubuntu-tegra/updates
 
 parts:
+  vpi-headers:
+    plugin: nil
+    source: headers/
+    override-pull: |
+      craftctl default
+      mkdir -p /usr/lib/include
+      cp *.h /usr/lib/include/
+    prime:
+      - -*
+
   vpi-samples:
+    after: [vpi-headers]
     plugin: nil
     build-packages:
+      - cuda-13-2
       - nvidia-vpi
-      - libnvvpi3
-      - python3.10-vpi3
-      - vpi3-samples
-      - vpi3-dev
+      - libnvvpi4
+      - python3.12-vpi4
+      - vpi4-samples
+      - vpi4-dev
       - libopencv-dev
       - libopencv
       - cmake
       - python3-numpy
       - python3-pil
       - libopencv-python
-      - libicu70
+      - libicu74
       - libegl1
     stage-packages:
-      - vpi3-samples
+      - vpi4-samples
       - libopencv-python
-      - python3.10-vpi3
+      - python3.12-vpi4
       - python3-numpy
       - python3-pil
     override-build: |
@@ -65,7 +78,7 @@ parts:
       L4T_DEB_PACKAGES_PATH=${L4T_DEB_PACKAGES_PATH:="NVIDIA_ARCHIVE"}
       if [ "$L4T_DEB_PACKAGES_PATH" = "NVIDIA_ARCHIVE" ]; then
         apt update
-        apt install --yes nvidia-l4t-cuda nvidia-l4t-pva nvidia-l4t-3d-core nvidia-l4t-multimedia
+        apt install --yes nvidia-l4t-cuda nvidia-l4t-pva nvidia-l4t-3d-core nvidia-l4t-multimedia nvidia-l4t-multimedia-utils nvidia-l4t-jetson-multimedia-api
       elif [ -d $L4T_DEB_PACKAGES_PATH ]; then
         apt install -y libegl1 nvme-cli efibootmgr bridge-utils libffi7 libasound2 libgles2 -f
         apt install -y alsa-topology-conf alsa-ucm-conf libasound2-data libdrm-amdgpu1 -f
@@ -83,10 +96,15 @@ parts:
         dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-wayland_*.deb
         dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-3d-core_*.deb
         dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-multimedia_*.deb
+        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-multimedia-utils_*.deb
+        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-jetson-multimedia-api*.deb
       fi
-      export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/lib/aarch64-linux-gnu/tegra-egl/
-      cd $CRAFT_PART_INSTALL/opt/nvidia/vpi3/samples/
-      for f in */CMakeLists.txt ; do pushd $(dirname $f) ; cmake -DOpenCV_DIR=/usr/lib/cmake/opencv4 . ; VERBOSE=1 make ; popd ; done
+      echo '/usr/local/cuda-13.2/compat' | tee -a /etc/ld.so.conf.d/000_cuda.conf
+      ldconfig
+      unset LD_LIBRARY_PATH
+      cd $CRAFT_PART_INSTALL/opt/nvidia/vpi4/samples/
+      CMAKE_OPTS="-DOpenCV_DIR=/usr/lib/cmake/opencv4 -DNvBuffer_INCLUDE_DIR=/usr/src/jetson_multimedia_api/include -DNvSci_INCLUDE_DIR=/usr/src/jetson_multimedia_api/include -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc"
+      for f in */CMakeLists.txt ; do pushd $(dirname $f) ; cmake $CMAKE_OPTS . && VERBOSE=1 make -j 2 || echo "Skipping $(dirname $f) - build failed" ; popd ; done
       for f in */CMakeLists.txt ; do pushd $(dirname $f) ; rm -fr CMakeFiles ; popd ; done
     override-prime: |
       craftctl default
@@ -106,95 +124,95 @@ apps:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/01-convolve_2d/vpi_sample_01_convolve_2d
+    command: /opt/nvidia/vpi4/samples/01-convolve_2d/vpi_sample_01_convolve_2d
   vpi-sample-02-stereo-disparity:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/02-stereo_disparity/vpi_sample_02_stereo_disparity
+    command: /opt/nvidia/vpi4/samples/02-stereo_disparity/vpi_sample_02_stereo_disparity
   vpi-sample-03-harris-corners:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/03-harris_corners/vpi_sample_03_harris_corners
+    command: /opt/nvidia/vpi4/samples/03-harris_corners/vpi_sample_03_harris_corners
   vpi-sample-04-rescale:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/04-rescale/vpi_sample_04_rescale
+    command: /opt/nvidia/vpi4/samples/04-rescale/vpi_sample_04_rescale
   vpi-sample-05-benchmark:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/05-benchmark/vpi_sample_05_benchmark
+    command: /opt/nvidia/vpi4/samples/05-benchmark/vpi_sample_05_benchmark
   vpi-sample-06-klt-tracker:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/06-klt_tracker/vpi_sample_06_klt_tracker
+    command: /opt/nvidia/vpi4/samples/06-klt_tracker/vpi_sample_06_klt_tracker
   vpi-sample-07-fft:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/07-fft/vpi_sample_07_fft
+    command: /opt/nvidia/vpi4/samples/07-fft/vpi_sample_07_fft
   vpi-sample-08-cross-aarch64-l4t:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/08-cross_aarch64_l4t/vpi_sample_08_cross_aarch64_l4t
+    command: /opt/nvidia/vpi4/samples/08-cross_aarch64_l4t/vpi_sample_08_cross_aarch64_l4t
   vpi-sample-09-tnr:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/09-tnr/vpi_sample_09_tnr
+    command: /opt/nvidia/vpi4/samples/09-tnr/vpi_sample_09_tnr
   vpi-sample-10-perspwarp:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/10-perspwarp/vpi_sample_10_perspwarp
+    command: /opt/nvidia/vpi4/samples/10-perspwarp/vpi_sample_10_perspwarp
   vpi-sample-11-fisheye:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/11-fisheye/vpi_sample_11_fisheye
+    command: /opt/nvidia/vpi4/samples/11-fisheye/vpi_sample_11_fisheye
   vpi-sample-12-optflow-lk:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/12-optflow_lk/vpi_sample_12_optflow_lk
+    command: /opt/nvidia/vpi4/samples/12-optflow_lk/vpi_sample_12_optflow_lk
   vpi-sample-13-optflow-dense:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/13-optflow_dense/vpi_sample_13_optflow_dense
+    command: /opt/nvidia/vpi4/samples/13-optflow_dense/vpi_sample_13_optflow_dense
   vpi-sample-14-background-subtractor:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/14-background_subtractor/vpi_sample_14_background_subtractor
+    command: /opt/nvidia/vpi4/samples/14-background_subtractor/vpi_sample_14_background_subtractor
   vpi-sample-15-image-view:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/15-image_view/vpi_sample_15_image_view
+    command: /opt/nvidia/vpi4/samples/15-image_view/vpi_sample_15_image_view
   vpi-sample-17-template-matching:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/17-template_matching/vpi_sample_17_template_matching
+    command: /opt/nvidia/vpi4/samples/17-template_matching/vpi_sample_17_template_matching
   vpi-sample-18-orb-feature-detector:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/18-orb_feature_detector/vpi_sample_18_orb_feature_detector
+    command: /opt/nvidia/vpi4/samples/18-orb_feature_detector/vpi_sample_18_orb_feature_detector
   vpi-sample-19-dcf-tracker:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/19-dcf_tracker/vpi_sample_19_dcf_tracker
+    command: /opt/nvidia/vpi4/samples/19-dcf_tracker/vpi_sample_19_dcf_tracker
   vpi-blur:
     command-chain:
       - bin/graphics-core22-wrapper
       - bin/vpi-wrapper
-    command: /opt/nvidia/vpi3/samples/tutorial_blur/vpi_blur
+    command: /opt/nvidia/vpi4/samples/tutorial_blur/vpi_blur
 
